services:
  # Backend Django
  backend:
    image: pdanielfg/tfg-backend:latest
    container_name: django_api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: practica
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  # Frontend Vue.js
  frontend:
    image: pdanielfg/tfg_frontend:latest
    container_name: vue_app
    ports:
      - "8080:80"
    depends_on:
      - backend

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_logs
    restart: always
    environment:
      MYSQL_DATABASE: practica
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
  sqlite_data:

