# Generated by Django 5.2.8 on 2025-11-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlLogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('thread_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_host', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=64, null=True)),
                ('command_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('sql_type', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('is_complex', models.BooleanField(default=False)),
                ('was_error', models.BooleanField(default=False)),
                ('raw', models.TextField()),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='logs_mysqll_timesta_4fd6e3_idx'), models.Index(fields=['command_type'], name='logs_mysqll_command_ee8376_idx'), models.Index(fields=['sql_type'], name='logs_mysqll_sql_typ_4e7981_idx'), models.Index(fields=['thread_id'], name='logs_mysqll_thread__c83540_idx')],
            },
        ),
    ]
