# Generated by Django 5.2.8 on 2025-11-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqllogline',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
