# Generated by Django 5.2.8 on 2025-11-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_mysqllogline_error_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqllogline',
            name='error_msg',
        ),
    ]
