# Generated by Django 5.2.8 on 2025-11-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_mysqllogline_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqllogline',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
