# Generated by Django 5.2.8 on 2025-12-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_mysqllogline_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqllogline',
            name='connection_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
