# Generated by Django 5.2.8 on 2025-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_mysqllogline_connection_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqllogline',
            name='logic_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mysqllogline',
            name='syntax_error',
            field=models.BooleanField(default=False),
        ),
    ]
